Support CDN
bizflycloud/gobizfly pull request #55
Opened 2021-01-26 04:28 UTC by tung491

2021-01-26 16:21 UTC, greatbn commented on cdn.go
> +	req, err := c.client.NewRequest(ctx, http.MethodGet, cdnName, strings.Join([]string{domainPath, domainID}, "/"), nil)
Can we use itemPath function in here ?

2021-01-26 16:22 UTC, greatbn commented on cdn.go
> +type BandwidthPrice struct {
what is this?

2021-01-26 16:22 UTC, greatbn requested changes

2021-01-26 16:22 UTC, greatbn commented on cdn.go
> +type UsageUser struct {
please check unused variable, struct?

2021-01-26 16:24 UTC, greatbn commented on cdn.go
> +	Pages   int      `json:"pages"`
Because these responses are paginate, Do you mind change the function to work with multiple pages?

2021-01-27 04:26 UTC, greatbn commented on client.go
>  	containerRegistryName   = "container-registry"
change the name to `container_registry`

2021-01-27 04:33 UTC, tung491 commented on client.go
>  	containerRegistryName   = "container-registry"
I have renamed it

2021-01-27 08:08 UTC, merged